on:
  push:
    branches:
    - master

  
name: Test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
